### ISSUE TITLE
SayKo_ Issue

### ISSUE THREAD

**Issue by AllahGamingYT** [DoktorSAS/GSC#2]
i get bocned to much when i use 🚑🚑🚒🚒 the 😲😲😧 shield bounce what🤬

**Comment by DoktorSAS** [comment]
What?

**Comment by AllahGamingYT** [comment]
bisicely when i use bonce shield ig et 😎😎🤣🤣 bonced too much out 🤑🤑🤑 the floor😨😨😨😭😭😱😱😱

**Comment by DoktorSAS** [comment]
There is a dvar to change it from powerfull to less powerfull just change sv_enablebounces values in your config

**Comment by AllahGamingYT** [comment]
fuck i got spotted

**Comment by AllahGamingYT** [comment]
😱😱😱😱

**Comment by AllahGamingYT** [comment]
@DoktorSAS can i get unbanned im sorry for what i did in ssorex

**Comment by DoktorSAS** [comment]
Nah

**Comment by AllahGamingYT** [comment]
i just  realised you had w@w servers digital jihad really gonna like that

**Comment by AllahGamingYT** [comment]
oh and s&d too

**Comment by DoktorSAS** [comment]
What you want do? DDOS them?

**Comment by AllahGamingYT** [comment]
ddos is cringe ill do even better, get them closed

**Comment by AllahGamingYT** [comment]
getting 1 server closed shouldnt be so hard considering i got sorex zombie and mp closed in a sec

**Comment by AllahGamingYT** [comment]
getting 1 server closed shouldnt be so hard considering i got sorex zombie and mp closed in a sec n

**Comment by DoktorSAS** [comment]
Okey, is all up to you

**Comment by AllahGamingYT** [comment]
just saying but remember when u cried in vc🤣🤣🤣

**Comment by DoktorSAS** [comment]
Yep, i did. Thanks for let me notice that

**Comment by AllahGamingYT** [comment]
mans cried over his bo2 server🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣
