### ISSUE TITLE
chatbank.gsc

### ISSUE THREAD

**Issue by mitchellurgero** [DoktorSAS/GSC#3]
How to use? It loads according to the cli, but I can't get any commands working? I see a prefix and such but nothing I try works.

**Comment by DoktorSAS** [comment]
Enable it. There 2 dvars that you need to turn on and off this feature.
sv_allowchatbank and sv_allowchatpayments

**Comment by mitchellurgero** [comment]
Thanks! I have those dvars both set to "1" in the cfg. How do I do the commands?

**Comment by DoktorSAS** [comment]
Both are valid way to enable it

**Comment by mitchellurgero** [comment]
Yeah but how do I use it once enabled? It's never explained in the readme???

**Comment by DoktorSAS** [comment]
With the command .w and .d, there also .p to pay another player if you enable it.
That script its just a simple script by reading you can find all the commands its not meant to ne a reasle since its just a basic script and nothing special.
