### ISSUE TITLE
.balance Not Working

### ISSUE THREAD

**Issue by Ahrimdon** [DoktorSAS/GSC#5]
All commands work flawlessly, except for ".balance". I've narrowed it down to this line of code here. When executing the command in game it prints "thisisatest". I'm guessing it just doesn't read from the file? Amazing script by the way, thank you for the hard work!
![Screenshot 2022-09-08 162411](https://user-images.githubusercontent.com/100532722/189218772-0093125e-495c-41ec-b34d-62bd8d3fdf48.png)

**Comment by DoktorSAS** [comment]
Issue should be patch on <https://github.com/DoktorSAS/GSC/commit/6cf4885b81301f3f929e3c271baa87bcf425a212> push.
Use the new code that add also dupe fixed and man other patches
