### ISSUE TITLE
.withdraw doesn't work despite not having whos who or last stand.

### ISSUE THREAD

**Issue by SwordSWD** [DoktorSAS/GSC#6]
![image](https://user-images.githubusercontent.com/62721069/218281696-13ae2d2c-9742-4237-8c85-7eeed42678e4.png)

Not sure if I am missing something but as you can see in the screenshot I'm not on my last stand or using Whos Who (Obviously since this is Buried)

**Comment by DoktorSAS** [comment]
Try to print the values of the player.whos_who_effects_active and player.fake_death and see which one exist and is true.
Check if other scripts are the cause of that issue.

Let me know the results

**Comment by SwordSWD** [comment]
There are no other scripts loaded onto the server and both of them showed no outputs. Still doing it tho

**Comment by DoktorSAS** [comment]
### Can't reproduce the issue
![image](https://user-images.githubusercontent.com/62484597/218335511-a9cc2d74-a825-4ca6-a05a-38ae22f9bb0c.png)
