### ISSUE TITLE
Autocompiler exe registers as Malware-Gen

### ISSUE THREAD

**Issue by TheFantasticLoki** [DoktorSAS/GSC#8]
Avast is marking the GSC Autocompiler as malware gen. I'd like an explanation of why or if this isn't supposed to happen and mine happened to get infected.

**Comment by DoktorSAS** [comment]
It is a false positive. The exe has been compiled with the lib [PS2EXE](https://www.powershellgallery.com/packages/ps2exe/1.0.10) and it happen to me to be flagged as a malware by some antivirus. 

The code that the exe is made from is the one contained in the compile.ps1 file.

The version with the provided exe its only for the old gsc compiler. To compile gsc now is better to use the gsc-tool by xensik.

If you download the correct version the exe will not be provided and you are safe that its not a virus.

https://github.com/DoktorSAS/GSC/blob/main/T6/GSC%20Autocompiler/GSC%20Auto-compiler%20with%20xensik%20compiler.rar


VirustTotal: https://www.virustotal.com/gui/file/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855/detection
