### ISSUE TITLE
Chatbank not working, Specifically in Transit server

### ISSUE THREAD

**Issue by ghost** [DoktorSAS/GSC#9]
Hello, 

I have 4 servers working fine with chatbank.gsc on Plutonium T6 but my latest (Tranzit) is not
container@pterodactyl~ Server marked as running...
Script "scripts/zm/chatbank-compiled.gsc" loaded successfully

******* script link error *******

**** 7 script error(s):
**** Unresolved external :  "fileexists" with 1 parameters in "chatbank" at line
s 1,1 ****
**** Unresolved external :  "writefile" with 2 parameters in "chatbank" at line
1 ****
**** Unresolved external :  "fopen" with 2 parameters in "chatbank" at lines
*********************************

**Comment by DoktorSAS** [comment]
The script is dependent on an external script called t6-gsc-utils that implement all those methods.

Here is the link to the project: https://github.com/fedddddd/t6-gsc-utils
